<template>
    <div>
        <p v-if="n() >= t">Aliquam eget quam fermentum, rhoncus sapien non, tincidunt mi. Vivamus lacinia, est eu dictum lobortis, lacus massa sagittis turpis, sed mattis odio erat id ipsum. Sed id tortor id massa tristique dignissim sed vel risus. Etiam porttitor diam erat, in volutpat nibh eleifend eu. Nunc tempor ex quis neque dapibus eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque vulputate massa dui, ac finibus nulla iaculis eget. Aenean auctor nisl a purus lobortis, at ornare tellus semper. Vivamus egestas blandit posuere. Maecenas eu dapibus risus. Pellentesque luctus dui vitae ullamcorper posuere. Morbi elementum semper diam, eu cursus felis iaculis ut.</p>
        <p v-if="n() >= t">Etiam ullamcorper eget urna non ornare. Nullam vehicula urna et laoreet aliquet. Integer lacinia ligula a augue iaculis, et egestas quam laoreet. Sed eget nunc at sapien ultricies semper. Ut lectus mauris, mollis sit amet dapibus nec, ultrices eu felis. Proin suscipit tempor luctus. Donec venenatis, libero eget vulputate pretium, est lacus luctus urna, ac congue mi urna id risus. Nulla quis mauris eget nunc laoreet convallis ut et nisl. Phasellus lacinia porttitor leo, eget iaculis est dictum sed. Nulla facilisi. Nullam dui mauris, tempor ac rhoncus at, congue quis risus. Sed consectetur nisi eget sem efficitur ultrices eu sit amet risus. Fusce suscipit blandit massa, in auctor lorem.</p>
        <p v-if="n() >= t">Vivamus quis lorem lacus. Curabitur semper tempus massa eget accumsan. Fusce in eros vehicula, suscipit urna vitae, laoreet lectus. Etiam a sodales est. Phasellus volutpat consequat neque, ut viverra nisl varius malesuada. Sed ac eros auctor, varius arcu eu, malesuada diam. Nullam commodo orci non lectus eleifend rutrum. Donec massa nunc, finibus eu accumsan at, placerat id lacus. Nulla in turpis dapibus nisi tempor porttitor quis sit amet velit. Ut tincidunt ex nec magna congue malesuada. Sed ornare, ante ac placerat sodales, tellus diam interdum leo, non tincidunt purus tortor eu tellus. Nunc id nulla euismod, condimentum elit quis, auctor orci. Etiam est purus, volutpat vitae elit at, maximus placerat erat. Curabitur aliquet tincidunt nunc, at porttitor magna consequat et. Praesent cursus tellus libero, quis tempor sapien pharetra a. Ut nec urna massa.</p>
        <p v-if="n() >= t">Vestibulum vehicula pellentesque sagittis. Maecenas facilisis sem erat, vitae efficitur ipsum congue id. Nunc fringilla nec mauris vitae mattis. Nullam lobortis vulputate convallis. Maecenas nec fringilla sapien. Fusce nec mi eu lacus varius viverra. Suspendisse sed sapien massa. Fusce nec quam id erat congue fermentum et nec odio. In tempor purus id lacinia auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam est ipsum, finibus at eros a, consequat imperdiet leo. Suspendisse porta est non est consequat blandit. Cras semper maximus elit et elementum. Ut feugiat a lectus id tristique.</p>
        <p v-if="n() >= t">Fusce hendrerit ac arcu vitae scelerisque. Integer nec sapien a justo congue sollicitudin. Vestibulum ac posuere ipsum. Suspendisse at lobortis ante. Nullam malesuada rhoncus est iaculis feugiat. Morbi turpis nisl, interdum sit amet ullamcorper id, sagittis nec ipsum. Aliquam blandit pulvinar mi, rhoncus aliquet mauris dignissim id. Aliquam fermentum est sit amet urna aliquet, at facilisis sapien sodales. Integer suscipit volutpat suscipit. Quisque lacinia rhoncus urna, id volutpat ante accumsan eget. In scelerisque ex vitae velit finibus sodales. Donec nunc quam, luctus nec rutrum faucibus, ultricies et arcu. Morbi dictum odio vel tellus vulputate, eu sollicitudin tortor aliquet. Nulla sit amet finibus odio.</p>
        <p v-if="n() >= t">Pellentesque tincidunt nibh varius urna porta facilisis. Aenean id lectus malesuada, bibendum est nec, egestas augue. Donec scelerisque egestas nibh, eu maximus felis feugiat a. In hac habitasse platea dictumst. Praesent gravida velit id varius maximus. Sed euismod semper tellus eget tempor. Suspendisse porta tellus eget eros dignissim egestas sed at risus. Vivamus viverra efficitur porta. Vivamus placerat posuere interdum. Fusce sit amet nulla eget justo rutrum laoreet vel et turpis. Vestibulum malesuada augue nec scelerisque vulputate.</p>
        <p v-if="n() >= t">Phasellus facilisis ac ipsum non congue. Nulla dapibus nisi arcu, in fringilla dolor cursus eget. Phasellus vitae pulvinar lacus. In hac habitasse platea dictumst. Morbi orci velit, posuere sit amet tellus eu, blandit dapibus lectus. Nullam sagittis arcu in metus rutrum euismod. Proin egestas libero laoreet urna luctus rutrum. Vestibulum venenatis, arcu ut sagittis maximus, magna elit congue nunc, eget mattis neque odio eu tellus. Phasellus sodales, nunc a imperdiet rhoncus, dolor dui efficitur enim, vel finibus risus libero vel sapien. Integer egestas venenatis accumsan. Sed scelerisque pharetra odio, vel auctor ligula consectetur sit amet. Aenean malesuada velit et odio auctor ultricies. Praesent et purus sit amet justo auctor lobortis.</p>
        <p v-if="n() >= t">Nulla commodo massa a tellus feugiat placerat. Morbi enim nisl, fermentum vitae venenatis nec, pharetra sed sem. Donec vehicula ultricies mauris, ut commodo sapien gravida quis. Phasellus tincidunt pretium rhoncus. Maecenas scelerisque nunc volutpat, aliquam nunc in, elementum odio. Mauris ac felis lorem. In malesuada odio vel leo egestas lacinia.</p>
        <p v-if="n() >= t">Nulla maximus erat elit, at blandit turpis condimentum vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec sit amet gravida leo, pulvinar interdum felis. Donec in interdum libero. Nam ac erat finibus, ornare urna vel, cursus felis. Maecenas sit amet sapien quis lectus faucibus mattis. Nullam pulvinar augue non ipsum rhoncus, ac sollicitudin nunc convallis. Morbi mollis nunc ut arcu ultricies rhoncus. Integer non ultrices nibh. Phasellus hendrerit sagittis nibh, sit amet ullamcorper magna imperdiet et.</p>
        <p v-if="n() >= t">Suspendisse potenti. Aenean rutrum tempus gravida. Integer ut varius metus, ut condimentum felis. Vestibulum mollis lacus vulputate velit iaculis, a mollis ipsum blandit. Proin at lorem ac elit facilisis eleifend. Duis laoreet mollis massa tempor tempus. Phasellus cursus magna quis nunc sodales, sed posuere mi laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec a sapien congue, congue enim eget, mattis ante. Vivamus at libero nibh. Nam sit amet odio dui. Ut fringilla arcu et lectus posuere elementum.</p>
        <p v-if="n() >= t">Mauris sit amet consectetur tortor, sed vulputate nunc. Nunc pellentesque ornare justo, vitae lobortis tellus luctus sed. Praesent molestie sodales turpis ac aliquam. Quisque eget ipsum vitae nisl rhoncus dapibus ac eu nisl. Pellentesque dui urna, malesuada at mi sed, euismod placerat orci. Curabitur pharetra purus rhoncus porttitor iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi auctor volutpat nibh, quis dictum ipsum dapibus nec. Pellentesque facilisis eros sem, sit amet lobortis eros aliquet at. Fusce ac consequat velit. Pellentesque id orci ac nisi malesuada ornare. Duis id nibh vel nulla elementum ultrices aliquet non leo. Donec sit amet tincidunt justo, nec semper leo. Nam hendrerit sem vitae molestie ultrices. Mauris mollis efficitur tincidunt.</p>
        <p v-if="n() >= t">Mauris sit amet nisi in mauris efficitur efficitur. Aliquam ipsum arcu, fermentum a quam vel, interdum ornare mauris. Cras commodo magna tortor. Morbi venenatis luctus augue. Proin sit amet lacinia metus, in commodo tortor. Suspendisse sit amet tortor interdum, commodo eros eget, sagittis nisi. Vestibulum congue, sem euismod auctor vestibulum, risus magna pellentesque libero, et sollicitudin urna tellus vitae purus. Nullam convallis orci urna, sit amet iaculis nunc semper ac. Donec sed fringilla dolor. Nam quis vulputate neque, eget cursus ipsum. Aliquam ut orci iaculis, ornare metus quis, sodales ipsum. Sed quis lacus tincidunt, auctor nulla quis, suscipit augue. Etiam egestas augue posuere sollicitudin porttitor. Vivamus at augue odio.</p>
        <p v-if="n() >= t">Ut aliquet, enim nec facilisis suscipit, libero ligula sagittis magna, ac hendrerit quam ipsum eget dui. Maecenas et sodales lectus, in interdum dolor. Suspendisse potenti. Etiam a felis metus. Cras ut efficitur lorem. Maecenas vulputate neque sem, sed porta diam faucibus a. Pellentesque dapibus vel risus vitae suscipit. Phasellus elementum, ligula vitae porta gravida, magna est sodales ligula, et imperdiet velit lectus vitae tellus. Nulla vel lacinia purus. Donec suscipit felis sed convallis iaculis.</p>
        <p v-if="n() >= t">Aenean ac urna bibendum, porta ligula et, sagittis dui. Ut id augue ligula. In ac justo eleifend, ullamcorper odio nec, volutpat nibh. Proin sollicitudin sit amet ligula eu sollicitudin. Maecenas tincidunt, ligula non rutrum congue, tellus augue scelerisque massa, ut finibus leo dolor sed nisl. Mauris vulputate dui in nunc commodo laoreet. Mauris tempor finibus porta.</p>
        <p v-if="n() >= t">Donec at tortor malesuada, facilisis tortor vitae, maximus nisl. Mauris faucibus, ante eget fringilla facilisis, metus lacus luctus augue, ac aliquam neque massa vitae justo. Duis eget arcu convallis, congue ex quis, ultricies diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean convallis laoreet tempus. Sed eget neque vel libero rhoncus molestie sed quis augue. Curabitur nunc eros, commodo ut odio pharetra, placerat convallis risus. In rhoncus ante quis magna tincidunt lobortis. Sed eleifend velit id turpis fringilla, in placerat nibh auctor. Nunc sed elementum nunc.</p>
    </div>
</template>

<script>
export default {
    props: {
        t: {type:Number, default: 8}
    },
    methods: {
        n() {return Math.round(Math.random() * 15)}
    }
}
</script>